services:
  database:
    image: 'postgres:latest'
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=liquibase_db'
      - 'POSTGRES_PASSWORD=oratiler'
    volumes:
      - '~/volumes/backebnd/postgres:/var/lib/postgresql/data'
